### ISSUE TITLE
provide a version constraint for the ricbra/robots-txt-bundle requirement

### ISSUE THREAD

**Issue by sherlyfebrianti96** [ricbra/robots-txt-bundle#1]
when i run this
composer require ricbra/robots-txt-bundle
it appears : Please provide a version constraint for the ricbra/robots-txt-bundle requirement
what should i do?

**Comment by ricbra** [comment]
Hi @sherlyfebrianti96 

That's strange. Perhaps your "minimum-stability" is on a different level than "dev"?

You could try version "^1.0@dev" which I get when running <code>composer require ricbra/robots-txt-bundle</code>.

**Comment by ricbra** [comment]
Closing this for now assuming the problem is solved.
